@rootURL = http://localhost:5000

### get all songs
GET {{rootURL}}/songs
Accept: application/json
### get secific song info
GET {{rootURL}}/songs/d5e720db-fb11-4fd8-8a6a-ab1973f6cc64
Accept: application/json
### create playlist
POST {{rootURL}}/playlist
Content-Type: application/json
{}
### get playlist by unique id
GET {{rootURL}}/playlist/45be158b-0791-4a9a-bf42-026e2155b8b7
Accept: application/json
### add song to specific playlist
POST {{rootURL}}/playlist/45be158b-0791-4a9a-bf42-026e2155b8b7/add/1
Content-Type: application/json
{}
### vote for a specific song in a playlist
POST {{rootURL}}/playlist/07a70fc8-5ca9-4683-9cb2-0b7e390f1272/vote/d5e720db-fb11-4fd8-8a6a-ab1973f6cc64
Content-Type: application/json
{}